### ISSUE TITLE
Add Talixo

### ISSUE THREAD

**Issue by SaraVieira** [SaraVieira/uber-cities#77]
https://talixo.com/

**Comment by Ma7eer** [comment]
If no one is working on this I can! Might be a bit later in the day but I can do it

**Comment by SaraVieira** [comment]
That would be great!

**Comment by Ma7eer** [comment]
I have a question. I looked up this company and the issue I have is they don't have a list of cities they operate in. I then contacted them and they said they don't give that information out (weird). They told me just type in the city you want through the website and claimed that this service is world wide. The issue is to type and check different cities is super tedious and hard. Another issue is this service isn't world wide because I did try to use it in my city and I couldn't. 

What should I do here?

**Comment by SaraVieira** [comment]
They didn't give the information ? That is weird .

Well. We tried, if someone knows we will open again but I'll close it because it's one them 

Thank you !!
